apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
  readiness:
    path: isready
    initialDelay: 10
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/dev/creds/sparkel-medlemskap
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvsparkelmedlemskap
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
  - name: KAFKA_CONSUMER_GROUP_ID
    value: sparkel-medlemskap-v1
  - name: KAFKA_RAPID_TOPIC
    value: helse-rapid-v1
  - name: AZURE_TENANT_ID
    value: 966ac572-f5b7-4bbe-aa88-c76419c0f851
  - name: AZURE_TENANT_BASEURL
    value: https://login.microsoftonline.com
  - name: MEDLEMSKAP_SCOPE
    value: api://496b0ded-cfdb-4430-b7b6-b568504de005/.default
